name: POI deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi.yml'

env:
  IMAGE_VERSION: '1.0'

defaults:
  run:
    working-directory: apis/poi/web

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    #  - name: Set up QEMU
    #    uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR
        uses: docker/login-action@v1 
        with:
          registry: anmopenhack.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anmopenhack.azurecr.io/openhack/poi:${{ env.IMAGE_VERSION }}.$GITHUB_RUN_NUMBER
