name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi.yml'

jobs:
  build_test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'apis/poi'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal 
    - name: create issue
      if: failure()
      run: |
        body="${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n"
        gh issue create --title "${{ env.build_name }} Workflow ${{ github.run_number }} Failed!" --body $body
          
